name: Deploy Test
on: [push, workflow_dispatch]
jobs:
  run-offline-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"

    - name: Install mpck
      run: |
        wget https://github.com/Sjord/checkmate/releases/download/v0.21/mpck_0.21-1_amd64.deb
        sudo dpkg --install mpck_0.21-1_amd64.deb

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r dev-requirements.txt

    - name: Run pytest
      run: |
        pytest test.py

  deploy-test-instance:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Copy repo contents to server via SCP
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        port: ${{ secrets.PORT }}
        key: ${{ secrets.SSHKEY }}
        source: "."
        target: "/var/www/littlesongplace-test"

    - name: Run test server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: |
          # Setup venv
          cd /var/www/littlesongplace-test
          python3 -m venv venv
          . venv/bin/activate
          pip install -r requirements.txt

          # Restart service
          sudo systemctl restart littlesongplace-test.service
